/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type SolutionsKnowledge = {
  /**
   * 问题
   */
  question: string;
  /**
   * 答案
   */
  answer: string;
  /**
   * 主题
   */
  subjects?: string[];
  /**
   * 参见
   */
  see_also?: string[];
}[];
